# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "../magic_rm", destination: "magic_rm"
  config.vm.provision "file", source: "../setup.py", destination: "setup.py"
  config.vm.provision "file", source: "../requirements.txt", destination: "requirements.txt"
  config.vm.provision "file", source: "../README.md", destination: "README.md"
  config.vm.provision "shell",
        inline: "sudo apt install -y python python-pip && sudo pip install setuptools && sudo ./setup.py install"
end